version: '3.7'

services:
  mariadb:
    image: mariadb:10.6.21
    environment:
      MYSQL_ROOT_PASSWORD: secret
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: secret
      # MYSQL_DATABASE: seven_twitter
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    restart: always
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
    ports:
      - "8080:80"

volumes:
  mariadb_data:
